default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
   # ref: https://github.com/mperham/sidekiq/issues/2985#issuecomment-531097962
  pool: <%= Sidekiq.server? ? ENV.fetch('SIDEKIQ_CONCURRENCY', 10) : ENV.fetch('RAILS_MAX_THREADS', 5) %>
  variables:
    # we are setting this value to be close to the racktimeout value. we will iterate and reduce this value going forward
    statement_timeout: <%= ENV["POSTGRES_STATEMENT_TIMEOUT"] || "14s" %>

development:
  <<: *default
  database: "<%= ENV.fetch('POSTGRES_DATABASE', 'postgres') %>"
  username: "<%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>"

test:
  <<: *default
  database: "<%= ENV.fetch('POSTGRES_DATABASE', 'postgres') %>"
  username: "<%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>"

production:
  <<: *default
  database: "<%= ENV.fetch('POSTGRES_DATABASE', 'postgres') %>"
  username: "<%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>"
